# Uncomment the next line to define a global platform for your project

platform :ios, '10.3'
use_frameworks!
xcodeproj 'kiwiSlangApp.xcodeproj'

 target 'kiwiSlangApp' do
    
	  pod 'SnapKit', '~> 4.0.0'
  	pod 'Fabric'
  	pod 'Crashlytics'
    pod 'Firebase/Core'
    pod 'Firebase/AdMob'
  	pod 'SwiftGen'
  	pod 'SwiftLint'
  	pod 'Koloda'
  	pod 'RealmSwift'    
    pod 'AFDateHelper', '~> 4.2.2'

    target 'KiwiSlangWidget' do
      inherit! :search_paths
      pod 'RealmSwift'
      pod 'AFDateHelper', '~> 4.2.2'
    end
end

  target 'kiwiSlangAppTests' do
    inherit! :search_paths
  end

  target 'kiwiSlangAppUITests' do
    inherit! :search_paths
  end