# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

 target 'kiwiSlangApp' do
  use_frameworks!
	pod 'SnapKit', '~> 4.0.0'
  	pod 'Fabric'
  	pod 'Crashlytics'
  	pod 'Firebase/Core'
  	pod 'Firebase/Messaging'
  	pod 'SwiftGen'
  	pod 'SwiftLint'
  	pod 'Koloda'
  	pod 'RealmSwift'
end

  target 'kiwiSlangAppTests' do
    inherit! :search_paths
  end

  target 'kiwiSlangAppUITests' do
    inherit! :search_paths
  end