# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kiwiSlangApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'SwiftGen'
  pod 'SwiftLint'

  target 'kiwiSlangAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kiwiSlangAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
