# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform :ios

platform :ios do
  before_all do
    
    # Setup Enviroment variables here:
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..." TO-DO: Set the hook with Slack
    # ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
    cocoapods
    
  end

############################################################################################################################################################################
  desc "KiwiSlang - BETA : Upload a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta_release do
    
    ENV["APP_IDENTIFIER"] = "com.sheinix.kiwiSlangApp"
    
    match(type: "appstore")
    increment_build_number
    #commit_version_bump
    gym(scheme: "kiwiSlangApp-Beta")
    pilot
  end
############################################################################################################################################################################
  desc "KiwiSlang - RELEASE : Upload a new release Build to Apple Appstore"
  desc "Deploy a new version to the App Store"
  lane :release do

    ENV["APP_IDENTIFIER"] = "com.sheinix.kiwiSlangApp"

    match(type: "appstore")
    #snapshot
    #frameit
    increment_build_number
    capture_ios_screenshots(
      skip_open_summary: true,
      clean: true,
      clear_previous_screenshots: true,
      reinstall_app: true)
    frame_screenshots(silver: true)
    gym(scheme: "kiwiSlangApp-AppStore") # Build your app - more options available
    deliver(precheck_default_rule_level: :error)
    #deliver(force: true)
    
  end
############################################################################################################################################################################
desc " -- Run the snapshots and Frame it --"
  lane :snapshots do
    capture_ios_screenshots(
      skip_open_summary: true,
      clean: true,
      clear_previous_screenshots: true,
      reinstall_app: true)
    frame_screenshots(silver: true)
  end
############################################################################################################################################################################
  desc "KiwiSlang - PRECHECK : Pre check before uploading to appstore"
  lane :check_metadata do
    precheck
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
